version: '3'

services:

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        volumes:
            - ./src:/var/www/html
            - ./conf/nginx/global:/etc/nginx/global
            - ./conf/nginx/site.template.conf:/etc/nginx/conf.d/site.template
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data/nginx-cache:/var/run/nginx-cache
        restart: always
        links:
            - php
            - mariadb

    php:
        build: ./.docker/php-fpm
        container_name: php
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
            - ./src:/var/www/html
            - ./data/nginx-cache:/var/www/nginx-cache

    mariadb:
        image: 'bitnami/mariadb:latest'
        container_name: mariadb
        restart: always
        environment:
            - MARIADB_ROOT_USER=${MYSQL_ROOT_USER}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MYSQL_DATABASE}
            - MARIADB_USER=${MYSQL_USER}
            - MARIADB_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - ./data/mysql:/bitnami

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mariadb

